#!/bin/bash

set -ex

# Ask for the administrator password upfront
sudo -v

# Set computer name (as done via System Preferences -> Sharing)
sudo scutil --set ComputerName "lucy"
sudo scutil --set HostName "lucy"
sudo scutil --set LocalHostName "lucy"
sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "lucy"

# Set profile preferences location for iterm2
defaults write com.googlecode.iterm2.plist PrefsCustomFolder -string "~/dotfiles/iterm2"
defaults write com.googlecode.iterm2.plist LoadPrefsFromCustomFolder -bool true

# Set some basic security settings.
defaults write com.apple.screensaver askForPassword -int 1
defaults write com.apple.screensaver askForPasswordDelay -int 0

# Create Developer directory in the user folder
mkdir ~/Developer

# Set 1.1.1.1 as default DNS servers
networksetup -setdnsservers Wi-Fi 1.1.1.1 1.0.0.1 2606:4700:4700::1111 2606:4700:4700::1001

# Add login screen message.
sudo defaults write /Library/Preferences/com.apple.loginwindow LoginwindowText "Found this computer? Please contact Magnus Bergman at karlmagnusbergman@gmail.com"

# Enable key repeat everywhere
defaults write -g ApplePressAndHoldEnabled -bool false

# Set a blazingly fast keyboard repeat rate
defaults write NSGlobalDomain KeyRepeat -int 1
defaults write NSGlobalDomain InitialKeyRepeat -int 15

# Disable automatic capitalization as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false

# Disable smart dashes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false

# Disable automatic period substitution as it’s annoying when typing code
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false

# Disable smart quotes as they’re annoying when typing code
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false

# Disable auto-correct
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false

# Hide scrollbars.
defaults write NSGlobalDomain AppleShowScrollBars -string "WhenScrolling"

# Enable full keyboard access.
defaults write NSGlobalDomain AppleKeyboardUIMode -int 2

# Hide files and directories on the desktop
defaults write com.apple.finder CreateDesktop -bool false

# New Finder windows shows Home directory
defaults write com.apple.finder NewWindowTarget -string "PfHm"
defaults write com.apple.finder NewWindowTargetPath -string "file:///Users/magnus/"

# Disable the warning when changing a file extension
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

# Keep folders on top when sorting by name.
defaults write com.apple.finder _FXSortFoldersFirst -bool true

# Minimize windows into application icon.
defaults write com.apple.dock minimize-to-application -bool true

# Hide recent applications in the dock.
defaults write com.apple.dock show-recents -bool false

# Set the icon size of Dock items to 50 pixels.
defaults write com.apple.dock tilesize -int 50

# Automatically hide and show the Dock.
defaults write com.apple.dock autohide -bool true

# Disable the dashboard feature.
defaults write com.apple.dashboard mcx-disabled -bool true

# Show week numbers in Calendar.app
defaults write com.apple.iCal "Show Week Numbers" -bool true

# Don't open Spotify at login
defaults write com.spotify.client AutoStartSettingIsHidden -bool false

# Revoke sudo access again
sudo -k
