#!/usr/bin/env bash

set -e

read -pr "This may overwrite existing files in your home directory. Are you sure? (y/n) " -n 1
echo
if [[ ${REPLY} =~ ^[Yy]$ ]]; then
  rsync -avh ./home/ "$HOME";
  chflags hidden "$HOME/bin";
fi;
